# Generated by Django 5.1.1 on 2024-12-03 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_subject_subjectmaks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmaks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentmaks', to='vege.student'),
        ),
    ]
